# Generated by Django 4.0.5 on 2022-06-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Votre nom')),
                ('email', models.EmailField(max_length=255, verbose_name='Votre adresse email')),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
