# Generated by Django 4.0.5 on 2022-06-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Infinity Media', max_length=255)),
                ('introduction', models.TextField()),
            ],
        ),
    ]
