# Generated by Django 4.0.5 on 2022-06-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_alternatif', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='logo')),
            ],
        ),
    ]
