# Generated by Django 4.0.5 on 2022-06-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.TextField()),
                ('image', models.ImageField(upload_to='partenaire/')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Direction',
            },
        ),
        migrations.CreateModel(
            name='Partnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partenaire', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='partenaire/')),
            ],
            options={
                'verbose_name': 'Nos partenaires',
                'verbose_name_plural': 'Nos partenaires',
            },
        ),
    ]
