# Generated by Django 4.0.5 on 2022-06-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_alter_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=255, unique=True, verbose_name='Titre du jeu')),
                ('game_image', models.ImageField(upload_to='game', verbose_name='Image')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Date de sortie')),
                ('game_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categorie', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
                'ordering': ['-timestamp'],
            },
        ),
    ]
